[package]
name = "molly"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.25.0"

[dev-dependencies]
chemfiles = "0.10.41"
xdrfile = "0.3.0"
bencher = "0.1.5"

[profile.release]
lto = true

[[bench]]
name = "bench"
harness = false
